name: CI/CD
run-name: text2img
on:
  push:
    branches:
      - "main"

jobs:

  update_notification:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: deploy
    
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
      - run: |
            sudo chmod +x .github/workflows/update_notifier.sh
            .github/workflows/update_notifier.sh BOT_API_KEY=${{ secrets.BOT_API_KEY }} CHAT_ID=${{ secrets.CHAT_ID }} PR_TITLE="${{ steps.PR.outputs.pr_title }}" REPOSITORY_NAME="${{fromJSON(steps.PR.outputs.pr).head.repo.full_name}}" DETAILS="${{ steps.PR.outputs.pr_body}}" DEVELOPER_LOGIN="${{ fromJSON(steps.PR.outputs.pr).user.login}}"

